security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/user/ulist, roles: ROLE_USER }
        - { path: ^/user/index, roles: ROLE_USER }
        - { path: ^/user/help, roles: ROLE_USER }
        - { path: ^/profile/edit, roles: ROLE_USER }


        - { path: ^/user/deleteUser.*, roles: ROLE_ADMIN }
        - { path: ^/user/addNewMem.*, roles: ROLE_ADMIN }
        - { path: ^/user/authList.*, roles: ROLE_ADMIN }

        - { path: ^/user/addDepartment.*, roles: ROLE_ADMIN }
        - { path: ^/user/deleteDepartment.*, roles: ROLE_ADMIN }



        - { path: ^/modules/modList.*, roles: ROLE_USER }
        - { path: ^/modules/dataList.*, roles: ROLE_USER }
        - { path: ^/modules/addData.*, roles: ROLE_USER }


        - { path: ^/modules/addMod, roles: ROLE_SUPER_ADMIN }
        - { path: ^/modules/adMod?moduleId.*, roles: ROLE_ADMIN }



        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: ROLE_ADMIN }
        - { path: ^/$, role: ROLE_USER }

