# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app_user.profile:
        class: AppBundle\EventListener\ProfileListener
        arguments: ~
        tags:
            - { name: kernel.event_subscriber }

    app_user.registration:
        class: AppBundle\EventListener\RegistrationListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }
    app.form.registration:
        class: AppBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: AppBundle\Form\Type\ProfileFormType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: app_user_profile }

    app.form.type.addmod:
        class: AppBundle\Form\Type\AddModFormType
        tags:
            - { name: form.type, alias: app_module_addmod }

    app.twig_extension:
        class: AppBundle\Twig\urldecodeExtension
        public: false
        tags:
            - { name: twig.extension, alias: app_url_decode_extension }