<?php
/**
 * Created by 火一五信息科技有限公司.
 * Tel :15288986891
 * QQ  :3186355915
 * web :http://host.huo15.com
 * User: apple
 * Date: 16/8/19
 * Time: 下午5:29
 */

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class AddModFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->add('name', 'text', array(
            'label' => '模块名称',
            'label_attr' => array(
                'class' => 'control-label'
            ),
            'attr' => array(
                'class' => 'form-control',
                'placeholder' => '请输入模块名称'
            )
        ))
            ->add('avatar', 'file', array(
                'label' => '图标logo',
                'label_attr' => array(
                    'class' => 'control-label'
                ),
                'required' => false,
                'data_class' => null,
                'attr' => array(
                    'class' => 'form-control'
                )
            ))
            ->add('brief', 'textarea', array(
                'label' => '模块简介',
                'label_attr' => array(
                    'class' => 'control-label'
                ),
                'required' => false,
                'attr' => array(
                    'class' => 'form-control'
                )
            ))
            ->add('save', SubmitType::class, array(
                'label' => '提交',
                'attr' => array(
                    'class' => 'form-control btn green',
                )
            ));

    }


    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Module',
        ));
    }
    public function getBlockPrefix()
    {
        return 'app_module_addmod';
    }
}