<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataRespository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataRespository extends EntityRepository
{
}
