<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlobalSetRespository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalSetRespository extends EntityRepository
{
}
