<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRespository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRespository extends EntityRepository
{
}
